name: Jediswap AMM Tests

on:
  push:
    branches: [ main, initial_poc ]
  pull_request:
    branches: [ main, initial_poc ]
  workflow_dispatch:
    

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install protostar
        run: curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash

      - name: Activate protostar
        run: source /home/runner/.bashrc

      - name: Help protostar
        run: protostar --help

      - name: Install protostar dependencies
        run: protostar install

      - name: Compile contracts
        run: protostar build

      - name: Run tests
        run: protostar test
